#pragma once
#include "quantum.h"

enum layers
{
  _A_BASE = 0,
  _A_NUM,
  _A_MATH,
  _A_SYM,
  _A_NAV,
  _A_RGB,
};

enum custom_keycodes
{
  BASE = SAFE_RANGE,
  A_BASE_JB,
  A_BASE_YH,
  A_BASE_CH,
  A_BASE_YN,
  A_BASE_FB,
  A_BASE_JT,
  A_BASE_NC,
  A_BASE_TF,
  A_BASE_NH,
  A_BASE_YC,
  A_BASE_TB,
  A_BASE_JF,
  A_BASE_BY,
  A_BASE_JH,
  A_BASE_BN,
  A_BASE_JC,
  A_BASE_TH,
  A_BASE_FY,
  A_BASE_BC,
  A_BASE_JN,
  A_BASE_FN,
  A_BASE_TC,
  A_BASE_TY,
  A_BASE_FH,
  A_NAV_FB,
  A_SYM_FB,
  A_NUM_TF,
  A_SYM_TF,
  A_NUM_JT,
  A_NAV_TF,
  A_NAV_JT,
  A_NUM_YN,
  A_NAV_NC,
  A_NAV_YN,
  A_NUM_NC,
  A_NAV_CH,
  A_BASE_SX,
  A_BASE_JY,
  A_BASE_BH,
  A_BASE_FC,
  A_BASE_TN,
  A_MATH_TF,
  A_SYM_NC,
  A_MATH_JT,
  A_SYM_CH,
  A_MATH_YN,
  A_MATH_NC,
  A_BASE_J = LT(_A_SYM, KC_J),
  A_BASE_T = KC_T,
  A_BASE_F = KC_F,
  A_BASE_B = LT(_A_NUM, KC_B),
  A_BASE_Y = LT(_A_RGB, KC_Y),
  A_BASE_N = KC_N,
  A_BASE_C = KC_C,
  A_BASE_H = LT(_A_MATH, KC_H),
  A_NUM_F = KC_4,
  A_NUM_T = KC_5,
  A_NUM_J = KC_6,
  A_NUM_H = KC_EQUAL,
  A_NUM_C = KC_1,
  A_NUM_N = KC_2,
  A_NUM_Y = KC_3,
  A_NUM_B = KC_NO,
  A_NAV_B = KC_LEFT,
  A_NAV_F = KC_DOWN,
  A_NAV_T = KC_UP,
  A_NAV_J = KC_RIGHT,
  A_NAV_H = OSM(MOD_LGUI),
  A_NAV_C = OSM(MOD_LALT),
  A_NAV_N = OSM(MOD_LCTL),
  A_NAV_Y = KC_ESC,
  A_SYM_B = KC_SLSH,
  A_SYM_F = KC_AMPR,
  A_SYM_T = KC_EXLM,
  A_SYM_J = KC_NO,
  A_SYM_H = KC_AT,
  A_SYM_C = KC_CIRC,
  A_SYM_N = KC_DLR,
  A_SYM_Y = KC_BSLASH,
  A_RGB_B = RGB_VAI,
  A_RGB_F = RGB_HUI,
  A_RGB_T = RGB_MOD,
  A_RGB_J = RGB_MOD,
  A_RGB_H = RGB_VAD,
  A_RGB_C = RGB_HUD,
  A_RGB_N = RGB_RMOD,
  A_RGB_Y = KC_NO,
  A_RGB_S = LSFT_T(KC_SPC),
  A_BASE_X = LT(_A_NAV, KC_BSPC),
  A_MATH_X = KC_BSPC,
  A_SYM_X = KC_BSPC,
  A_RGB_X = KC_BSPC,
  A_BASE_S = LSFT_T(KC_SPC),
  A_MATH_S = LSFT_T(KC_SPC),
  A_SYM_S = LSFT_T(KC_SPC),
  A_NUM_X = KC_PDOT,
  A_NUM_S = LSFT_T(KC_SPC),
  A_NAV_S = LSFT_T(KC_SPC),
  A_NAV_X = KC_NO,
  A_MATH_B = KC_NLCK,
  A_MATH_F = KC_ASTR,
  A_MATH_T = KC_LPRN,
  A_MATH_J = KC_PLUS,
  A_MATH_H = KC_RSFT,
  A_MATH_C = KC_PSLS,
  A_MATH_N = KC_RPRN,
  A_MATH_Y = KC_MINS,
};
